✨:: 태그 컴포넌트 완성
AI-Expo-2023/Chromatica-Client-V1 pull request #14
Opened 2023-03-23 14:12 UTC by kangjinhyeon1

✨:: 태그 컴포넌트 완성

2023-03-23 14:15 UTC, Ulement92 reviewed
yarn.rock 은 풀리퀘 안한다고 하시지 않으셨어요?

2023-03-23 14:17 UTC, Ulement92 approved these changes
good 버튼 나이스

2023-03-23 14:18 UTC, applely25 requested changes
태그 컴포넌트 코드만 올려주세요

2023-03-24 01:38 UTC, eternrust approved these changes

2023-03-24 02:28 UTC, closed without merging